language: generic

sudo: required

branches:
  only:
    - master
    - /^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$/

notifications:
  email:
    on_success: never
    on_failure: change

services:
  - mysql

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - COMPOSER_NO_INTERACTION=1
  matrix:
    - WP_VERSION=nightly
    - WP_VERSION=latest
    - WP_VERSION=4.9.4

matrix:
  allow_failures:
    - php: nightly
    - env: WP_VERSION=nightly
  fast_finish: true

before_install:
  # Uninstall phpenv
  - rm -dfr "${HOME}/.phpenv"

  # Install PHP7.2
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get -qq update
  - sudo apt-get install -y php7.2 php7.2-common php7.2-mbstring php7.2-gd php7.2-curl php7.2-xml php7.2-mysql
  - php -v

  # Install composer
  - cd "${HOME}"
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - sudo cp composer.phar /usr/bin/composer
  - cd "${TRAVIS_BUILD_DIR}"
  - composer --version

install:
    # Install helper scripts & WordPress
  - travis_retry composer global require --prefer-dist --no-suggest typisttech/travis-nginx-wordpress
  - export PATH=$HOME/.composer/vendor/bin:$PATH
  - tnw-install-wordpress
  - wp cli info

  - travis_retry composer install

script:
  - composer test
